### ISSUE TITLE
issue#1 links doesn't work in mobile/media view

### ISSUE THREAD

**Issue by Tilak3D** [codrops/LinesToLayout#2]
![Untitled](https://user-images.githubusercontent.com/109524845/185961919-91a37958-6d54-4582-b3c7-9bf0e025d367.png)

links doesn't work in mobile/media view

ps: Thanks for the opensource contribution you're into

**Comment by crnacura** [comment]
Hi @Tilak3D Thank you so much for posting the issue! I think we are in the wrong repo :) I've fixed the CSS for this and now it should work: https://github.com/codrops/ContentLayoutTransition/commit/ef96cdc22f1d7b8b426f73283c6c70e163eb9b29

Thanks again!

**Comment by Tilak3D** [comment]
> Hi @Tilak3D Thank you so much for posting the issue! I think we are in the wrong repo :) I've fixed the CSS for this and now it should work: [codrops/ContentLayoutTransition@ef96cdc](https://github.com/codrops/ContentLayoutTransition/commit/ef96cdc22f1d7b8b426f73283c6c70e163eb9b29)
> 
> Thanks again!

I don't know how it happen, Sorry for the inconvenience caused. And Thanks, btw i like your design intents, you're a gem!
